name: Docformatter-Black-Pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint docformatter black pytest

      - name: Run docformatter
        run: |
          docformatter --config config.toml --in-place --recursive $(git ls-files '*.py')

      - name: Run black
        run: |
          black --config config.toml --line-length 100 $(git ls-files '*.py')

      - name: Analyzing the code with pylint
        run: |
          pylint --rcfile=config.toml $(git ls-files '*.py')
